baseURL = 'https://scottlorimor.com/'
locale = 'en-us'
title = 'Scott Lorimor'
disableKinds = ['taxonomy', 'term']

[params]
  name = 'Scott Lorimor'
  bio = 'I do stuff.'
  interests = ['stuff', 'stuff', 'stuff']
  github = 'https://github.com/scottlorimor'
  linkedin = 'https://www.linkedin.com/in/scottlorimor/'
  email = 'scott@scottinabox.com'
  umamiURL = 'https://cloud.umami.is/script.js'
  umamiWebsiteID = '884ffada-8e32-482c-a2b3-6ffded450356'